### ISSUE TITLE
iOS upload window: progress indicator

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#171]
Maybe a progress bar : 
- 20% start
- 40% gcs urls retrieved
- 40%->100% : upload data progress

Or small circles : 
- 1 start
- 2 gcs urls retrieved
- 3 -> 5 : upload data progress

**Comment by Deleplace** [comment]
Or a portion of the photo being uploaded: see #253

**Comment by Bartalog** [comment]
- 4% start
- 10% downscaled
- 25% fetched signed URLs
- 25%->100% : upload data progress

Blue during upload, green when reaches 100%.
