### ISSUE TITLE
iOS splash on iPad: not locked on Portrait

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#173]
![ipad landscape](https://cloud.githubusercontent.com/assets/13508141/24334569/9605d0fe-126c-11e7-9b2c-4c5739569bc4.png)

**Comment by Bartalog** [comment]
All other views are "not portrait locked" as well :(

**Comment by Bartalog** [comment]
https://stackoverflow.com/a/33454271/871134
