### ISSUE TITLE
iOS Multiple upload

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#187]
At worst: display error "Multiple share is currently not available".

At slightly less worse: try to prevent having Cool Maze icon on multiple sharing, if technically possible.

At best: perform all of the downloads, just like the Android app already does.

(Any of the above would be better than not handling anything at all)

**Comment by Deleplace** [comment]
Each upload should still benefit individually from the hash-based optimization opportunity (#176).

**Comment by Deleplace** [comment]
Now implemented: "worst".

**Comment by Deleplace** [comment]
This may help for the "slightly less worse": https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW8

**Comment by Deleplace** [comment]
Now implemented "slightly less worse" : max 1 attachment, otherwise CM doesn't show up in the list.

**Comment by Bartalog** [comment]
It may help to use shortened resource URIs (when share extension opens containing app).

**Comment by Bartalog** [comment]
Implementation: consider letting the share extension upload a ZIP, and pass a single "resource" to the main app.

**Comment by Deleplace** [comment]
Implemented, at last
