### ISSUE TITLE
iOS: Uploading photo without downscaling

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#202]
Give the user the possibility to "turn off" the automatic downscaling of pictures bigger than 1600x1200, i.e. to upload to original big file.

**Comment by Deleplace** [comment]
UX may be this: "After successful resized upload, add button [Send original 6000x2000 picture (4MB)]"

**Comment by Bartalog** [comment]
Implemented as a user setting, in release 1.1.0
