### ISSUE TITLE
Android: Uploading photo without downscaling

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#203]
Give the user the possibility to "turn off" the automatic downscaling of pictures bigger than 1600x1200, i.e. to upload to original big file.

**Comment by Deleplace** [comment]
UX may be this: "After successful resized upload, add button [Send original 6000x2000 picture (4MB)]"

**Comment by Deleplace** [comment]
Informing about full picture image size, and dimensions, **and expected upload time** would be nice (full upload time inferred from upload time of the smaller version).

**Comment by Bartalog** [comment]
Implemented: as a Setting (default: downscaling enabled).
