### ISSUE TITLE
Download all, as zip

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#234]
ZIP may be generated server-side, or client-side in JS.

**Comment by Deleplace** [comment]
Client-side: https://stuk.github.io/jszip/ looks nice

**Comment by Bartalog** [comment]
The jszip npm package increases the React build of 150KB uncompressed, 44KB compressed, which is ... expensive : +50% !!

For such a niche feature (useful only with multiple resources use case), it would be good to find a more lightweight solution, at least when the feature is not used.

**Comment by Bartalog** [comment]
Also, jszip may not be trivial to use without jQuery, which add 30KB compressed.
