### ISSUE TITLE
Android: attach thumbnail to /dispatch

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#279]
Even if resource has already been fully uploaded!
Useful when target has poor internet.

Drawback: dispatch request ~8k instead of ~1k

**Comment by Bartalog** [comment]
This would also help #309 Inappropriate photo filter, because a thumbnail (~256px wide) is perfect to quickly check for inappropriateness.

**Comment by Bartalog** [comment]
In some cases, the extra 7KB would be sent twice: with `/scanned` and with `/dispatch`.
It's the price to pay, to save the workflow from yet another headache.
