### ISSUE TITLE
Android Handle response with "Please upgrade app"

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#281]

**Comment by Bartalog** [comment]
In response from what request? `/wakeup`, `/new-gcs-urls`, `/dispatch`?
Or a new specific request just for that?

**Comment by Bartalog** [comment]
Once the obsolescence has been detected, offer to open `https://play.google.com/store/apps/details?id=net.coolmaze.coolmaze`.

Be careful with the app id, see #294

**Comment by Bartalog** [comment]
```
        Intent playStoreIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=net.coolmaze.coolmaze"));
        startActivity(playStoreIntent);
```

**Comment by Bartalog** [comment]
Implemented on `/dispatch` response (success only, for now).
