### ISSUE TITLE
HM: lost internet connectivity -> don't remove QR

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#285]
When losing internet connectivity _before_ uploading a file, it make sense to hide the upload widgets.

But when the file has _already_ been uploaded, and QR-code is displayed, then we should ignore the "lost internet" event, and keep the QR on screen. 

The mobile device may still have a perfectly cromulent connectivity on its side.

**Comment by Bartalog** [comment]
Related: #475
