### ISSUE TITLE
Android : Show upload progress

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#30]
Display some kind of progress bar after the scanning, on the [Uploading...] screen.

**Comment by Deleplace** [comment]
Also, #144 may display some hint _before_ the scanning is complete.

**Comment by Deleplace** [comment]
In android-async-http "There is no progress implementation for out-going traffic so far" : 
https://github.com/loopj/android-async-http/issues/711

**Comment by Bartalog** [comment]
An interesting workaround is to instrument a custom `InputStream` which keeps track of its flow of data.
While this is technically cheating, the flow progress is almost accurate because the buffer size used in android-async-http is small: 4KB only.  Thus, we're not cheating by more than 4KB.

**Comment by Bartalog** [comment]
With above workaround, we're waaay more than 4KB off, probably because of heavier buffering somewhere in the mobile.

**Comment by Bartalog** [comment]
Implemented : imperfect (not very precise) progress bar.
