### ISSUE TITLE
Support Web Share API

### ISSUE THREAD

**Issue by beaufortfrancois** [Bartalog/cool-maze#317]
Steps to reproduce:

1. Go to https://beaufortfrancois.github.io/sandbox/media-recorder/mustache.html on Chrome for Android
2. Record video and hit "Share" button
3. Share with CoolMaze
4. Scan

What is the expected result?
I should be redirected to the recorded video.

What happens instead?
```Check out my new style! https://storage.googleapis.com/pwa-mustache/2017-10-03T08:00:47.266Z.webm```

![screenshot 2017-10-03 at 10 04 31 am](https://user-images.githubusercontent.com/634478/31115361-4d97a9d6-a822-11e7-80d4-aea91b5dff20.png)

@Bartalog

**Comment by Deleplace** [comment]
This would be nice to have too: #318 Hyperlinks in text messages

**Comment by Bartalog** [comment]
Let's say this is for Android only (afaik Web Share API is not supported at all in iOS).

**Comment by Bartalog** [comment]
> To convert data to a format suitable for ingestion into the target, the user agent SHOULD map the fields of ShareData onto equivalent concepts in the target. It MAY discard fields if necessary. 

https://wicg.github.io/web-share/

**Comment by Bartalog** [comment]
> Mapping the ShareData to the share target (or operating system)'s native format can be tricky as some platforms will not have an equivalent set of fields. For example, if the target has a "text" field but not a "URL" field, one solution is to concatenate both the text and url fields of ShareData and pass the result in the "text" field of the target.

**Comment by Deleplace** [comment]
Chrome seems to set an extra having key "org.chromium.chrome.extra.TASK_ID".
[l.86](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/share/ShareHelper.java?l=86)
[l.620](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/share/ShareHelper.java?rcl=07513e0abea6e130fc627a17da630df5f296e8e0&l=620)

Let's look for this extra and apply workaround "ok, if this ends with a URL, just go with the URL."

**Comment by beaufortfrancois** [comment]
And it works great ;)
