### ISSUE TITLE
No share in Chrome iOS

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#320]
Icon [Cool Maze] not in the list

**Comment by Bartalog** [comment]
That is tough
- https://stackoverflow.com/questions/30052099/ios-share-extension-in-chrome
- https://stackoverflow.com/questions/31855779/share-extension-is-not-working-in-chrome

**Comment by Bartalog** [comment]
OK, this should od the trick:
- https://stackoverflow.com/a/43250616/871134
