### ISSUE TITLE
Make sure "Download all as zip" leverages cached photos

### ISSUE THREAD

**Issue by Bartalog** [Bartalog/cool-maze#338]
(When #234 will be implemented)
Multiple pictures show up (full files) as tiles, as they become available.
When button "Download" is shown, and then the user clicks it, most pictures are probably already in the browser cache.
Check that the cached pictures are used to create the ZIP, instead of downloading them all again.

**Comment by Bartalog** [comment]
Chrome makes requests and gets back 304 codes, which is fine.

**Comment by Bartalog** [comment]
Firefox download all the photos a second time :(
It doesn't leverage ETags...

**Comment by Bartalog** [comment]
Note that this problem doesn't exist when using E2EE.

**Comment by Deleplace** [comment]
Obsolete now that E2EE is enforced by default in the Android and iOS apps
