### ISSUE TITLE
After scanning wrong QR (Android)

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#356]
Current: share is aborted.

Desired: go back to scan screen (camera) for 2nd chance.

**Comment by Bartalog** [comment]
Implemented for text message or single resource share.

**Comment by Deleplace** [comment]
Currently not working.

**Comment by Deleplace** [comment]
Still not working.

Phone vibrates, error message is not displayed at all, camera keeps filming.

**Comment by Deleplace** [comment]
Maybe a Toaster would do the job
