### ISSUE TITLE
Fallback: resource URL

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#364]
If the mobile source has correctly sent its message (uploaded its file) to the server, but fails to notify to the correct QR-key due to network problems ...
then it would be nice to be able to show a (reasonably short) URL on the mobile, and type it manually on the target computer, to retrieve the message.

**Comment by Bartalog** [comment]
This doesn't play very well with E2EE (#58)

**Comment by Bartalog** [comment]
It _should_ work with an encrypted file.
However, it's not clear why and how often the server push delivery fails, while the target browser has proper connectivity.

**Comment by Deleplace** [comment]
Probably not needed
