### ISSUE TITLE
Download all as ZIP: broken

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#369]
- Select 7 photos in Android gallery (with [Resize pictures] setting OFF)
- Share with Cool Maze
- Scan
- Click [Download all as ZIP]

Expected
- Downloaded ZIP contains all the files

Current
- Downloaded ZIP contains only 1 file

**Comment by Deleplace** [comment]
Maybe it's trying to store all files with the same conflicting filename `coolmaze-shared-content.jpg`?

**Comment by Bartalog** [comment]
This seems to be caused by the conflicting generic filename chosen by the Android app when the resource name can't be determined. Not related to the pictures being resized or not.
