### ISSUE TITLE
Resize pictures in background tasks

### ISSUE THREAD

**Issue by Bartalog** [Bartalog/cool-maze#375]
For some reason, this code
```
        new IntentIntegrator(this)
                .setOrientationLocked(true)
                .addExtra("PROMPT_MESSAGE", Config.SCAN_INVITE)
                .initiateScan();
```
doesn't _immediately_ open the QR scanner view. Some expensive work (thumnailing, resizing) that follows in the code of the main activity is executed (and effectively blocks the UI thread), before the user can start to scan.

Find a way to
- display the QR scanner asap
- NOT block the UI thread during expensive computations (which prevent the scanner from working even if it's in the foreground!!)

**Comment by Deleplace** [comment]
Implemented: use a `Handler` to "yield" after each resize. Use an `ExecutorService` to submit each resize task. Our current code still interferes with the main/UI thread (blocking on `Future.get()`) but it's now possible to successfully scan during the resizings.

**Comment by Deleplace** [comment]
Closing, but we may still want to implement genuinely async resize tasks.

**Comment by Deleplace** [comment]
Implemented: concurrent resize tasks. Faster than before, and less interfering with the main/UI thread.

**Comment by Deleplace** [comment]
Implemented for Multiple share only, for now. For Single share, see #539
