### ISSUE TITLE
Android Dark Theme

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#410]
Android Q comes with a Dark theme feature.

Please find a way to have black backgrounds instead of white, when Dark theme is enabled.

**Comment by Deleplace** [comment]
The Verge says:

> For third-party developers, Google is creating an API to let apps know when Dark Theme is on. It’s also giving developers the option of adding a single line of code to their apps to create a quick-and-dirty dark theme. If a developer chooses to use it, their app will simply have its colors inverted when Dark Theme is enabled.

**Comment by Bartalog** [comment]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme?hl=fr

**Comment by Bartalog** [comment]
Dark Theme is a new feature in Android Q, and

> ```Version 28 (intended for Android Pie and below) is the last version of the legacy support library, so we recommend that you migrate to AndroidX libraries when using Android Q and moving forward. The IDE can help with this: Refactor > Migrate to AndroidX...```

thus we need to migrate to AndroidX first.

**Comment by Bartalog** [comment]
Some basic parts may be working even without AndroidX, but WebViews and Toolbars will be tricky to get right.
