### ISSUE TITLE
Measure encryption time (tte) and decryption time (ttd) (Android)

### ISSUE THREAD

**Issue by Bartalog** [Bartalog/cool-maze#431]
Does encryption account for a large share of the total latency?

If so, consider explicit visual steps "Encrypting..." in the mobile app and "Decrypting..." in the web page.

**Comment by Bartalog** [comment]
Web: done, for single share only.

**Comment by Bartalog** [comment]
Android: done, for single share only.

**Comment by Deleplace** [comment]
Open a new issue for iOS, when the iOS app actually does encryption (as of 2022-02, it does not).
