### ISSUE TITLE
QR code overflows on mobile

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#560]
When accidentally clicking on the QR code at coolmaze.io using a mobile device (smaller screen), the QR code gets bigger and overflows the viewport boundaries. As a result, it can't be scanned anymore.

<img width="392" alt="image" src="https://github.com/Bartalog/cool-maze/assets/13508141/5f7d26e4-1864-4fea-b17b-378afca8a57b">

**Comment by Deleplace-juliette** [comment]
Yes, I saw this incident. To correct this problem, you have to click on the qr code on the mobile and the qr code returns to a normal size

**Comment by Deleplace** [comment]
Fixed
