### ISSUE TITLE
BUG IOS17 COOL MAZE 

### ISSUE THREAD

**Issue by julessup** [Bartalog/cool-maze#582]
I use Cool Maze with iPads and since the iOS 17.4 update I can no longer read the QRcode on my PC.
is this a bug?
configuration problem?
thanks

**Comment by Deleplace** [comment]
Thank you @julessup for reporting this important bug.

I confirm that Cool Maze for iPad used to work fine up to iOS 17.3.1, and is now failing on iOS 17.4 with Cool Maze 1.2.1.

The latest version of Cool Maze is 1.3.0 but I don't have data yet for (iOS 17.4 + Cool Maze 1.3.0). This latest version does not contain a specific fix for the QR code problem.

Cool Maze for iPhone is unaffected (working fine) even with iOS 17.4.

**Comment by julessup** [comment]
thank you for your reply. version 1.3 does not work on our ipads either. Do you think a fix will be available soon?
Sincerely

-------- Message d'origine --------De : Valentin Deleplace ***@***.***> Date : 12/03/2024  17:54  (GMT+01:00) À : Bartalog/cool-maze ***@***.***> Cc : julessup ***@***.***>, Mention ***@***.***> Objet : Re: [Bartalog/cool-maze] BUG IOS17 COOL MAZE  (Issue #582) 
Thank you @julessup for reporting this important bug.
I confirm that Cool Maze for iPad used to work fine up to iOS 17.3.1, and is now failing on iOS 17.4 with Cool Maze 1.2.1.
The latest version of Cool Maze is 1.3.0 but I don't have data yet for (iOS 17.4 + Cool Maze 1.3.0). This latest version does not contain a specific fix for the QR code problem.
Cool Maze for iPhone is unaffected (working fine) even with iOS 17.4.

**Comment by Deleplace** [comment]
Unfortunately I'm having problems with incompatible combinations of iOS version -> iOS SDK version -> Xcode version -> macOS version -> mac hardware version. I won't be able to properly debug and fix this issue until I buy a new dev workstation.

It would help a little bit if you could [take a screencast](https://support.apple.com/en-us/HT207935) of your experience so I can better understand what part of the code is failing and research from there.

**Comment by Deleplace** [comment]
This can be a regression in the app itself since version 1.2.1.

There was 1 share action from an iPad with iOS 17.4 and Cool Maze 1.1.4, and it was successful.

**Comment by julessup** [comment]
screencast : https://we.tl/t-Q5SFHKwQGe

**Comment by Deleplace** [comment]
Thank you, this is very helpful.  I was afraid the camera would not start at all because of stricter enforcement of some limitations of Share Apps by iOS. Fortunately, the camera is starting and the root cause of the problem seems to be something else.

**Comment by Deleplace** [comment]
I have not found the root cause of the releases (1.2.1, 1.3.0) failing on iPadOS 17.4.

In 2024, this bug has affected 4% of the iPad users of Cool Maze (0.07% of the Cool Maze total audience).

Fortunately, the problem seems to not occur anymore with subsequent iPadOS versions: 17.4.1, 17.5, 17.5.1. It has not been occuring at all for several months, probably because devices have automatically upgraded their OS version.

Please reach out if you're still impacted!
