### ISSUE TITLE
Smoother spinner

### ISSUE THREAD

**Issue by Deleplace** [Bartalog/cool-maze#80]
Current spinner is not great: sharp borders, white tail instead of transparent tail.

[https://github.com/Deleplace/cool-maze/blob/master/site/static/img/red_spinner.gif]

**Comment by Deleplace** [comment]
White square spinner background slightly mitigates the ugliness.

**Comment by Bartalog** [comment]
In React SPA, the indicator doesn't spin inside the QR-code.
It spins inside the topbar, which is fine.
